//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UdemyMVC5Proje.Models.EntitiFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VTMvcOkulEntities : DbContext
    {
        public VTMvcOkulEntities()
            : base("name=VTMvcOkulEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLDersler> TBLDersler { get; set; }
        public virtual DbSet<TBLKulup> TBLKulup { get; set; }
        public virtual DbSet<TBLNotlar> TBLNotlar { get; set; }
        public virtual DbSet<TBLOgrenci> TBLOgrenci { get; set; }
    }
}
