//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UdemyMVC5Proje.Models.EntitiFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLNotlar
    {
        public int NOTID { get; set; }
        public Nullable<byte> DERSID { get; set; }
        public Nullable<int> OGRID { get; set; }
        public Nullable<byte> VIZE { get; set; }
        public Nullable<byte> FINAL { get; set; }
        public Nullable<byte> PROJE { get; set; }
        public Nullable<decimal> ORTALAMA { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        public virtual TBLDersler TBLDersler { get; set; }
        public virtual TBLOgrenci TBLOgrenci { get; set; }
    }
}
